# Generated by Django 4.1.7 on 2023-05-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
    ]
