# Generated by Django 4.1.7 on 2023-04-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsapp', '0003_alter_registration_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.PositiveIntegerField(max_length=10, unique=True),
        ),
    ]
