# Generated by Django 4.1.7 on 2023-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsapp', '0002_remove_registration_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
    ]
