# Generated by Django 4.1.7 on 2023-04-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsapp', '0004_alter_registration_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
